### ISSUE TITLE
Can't use method repo.getPathEntry and repo.getPathsEntries

### ISSUE THREAD

**Issue by zolotyh** [discoveryjs/scan-git#7]
My code
```
const repo = await createGitReader(
  path.join(REPO_PATH, GIT_SERVICE_FOLDER_NAME)
);
const fileList = await repo.listFiles();
const fileInfo = await repo.getPathsEntries(fileList.at(0));
```

Error: 
```
file:///Users/zolotyh/sandbox/git-technical-dept/debug.js:12
const fileInfo = await repo.getPathsEntries(fileList.at(0));
TypeError: repo.getPathsEntries is not a function
```

It looks like the typescript wasn't built

NPM version

<img width="874" alt="Cursor" src="https://github.com/discoveryjs/scan-git/assets/432913/0f273e96-8dc9-4ddb-a74c-be20ab26e105">

Github version

<img width="1216" alt="Cursor" src="https://github.com/discoveryjs/scan-git/assets/432913/732d8c6e-9670-4eab-8968-7ff45c76165b">

**Comment by lahmatiy** [comment]
It was unpublished (marked as `next` in a change log). Just released as part of [0.1.2](https://github.com/discoveryjs/scan-git/releases/tag/v0.1.2)
